services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.vite
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_HMR_PORT: 5173
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/__pycache__/
    environment:
      FLASK_APP: api.py
      FLASK_DEBUG: "1"
      MONGO_URI: "mongodb://admin:password@mongodb:27017/mi_base_de_datos?authSource=admin"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
